"""Create ingestion logs table

Revision ID: 53d9b7fb7c8f
Revises: 81dc4f93eb3c
Create Date: 2025-11-27 16:53:25.567220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d9b7fb7c8f'
down_revision: Union[str, Sequence[str], None] = '81dc4f93eb3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
