"""Add embedding column to papers

Revision ID: 76c51b88cb8d
Revises: ae62dc0bf4ea
Create Date: 2025-11-27 16:33:28.154515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '76c51b88cb8d'
down_revision: Union[str, Sequence[str], None] = 'ae62dc0bf4ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "papers",
        sa.Column("embedding", Vector(384), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'embedding')
    op.create_table('ingestion_logs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('query', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('pages_processed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('papers_added', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('ingestion_logs_pkey'))
    )
    # ### end Alembic commands ###
