"""Expand papers schema for ingestion

Revision ID: ba5fe91f8a9e
Revises: 
Create Date: 2025-11-27 13:32:47.695493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba5fe91f8a9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('external_id', sa.String(), nullable=False))
    op.add_column('papers', sa.Column('doi', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('citation_count', sa.Integer(), nullable=False))
    op.add_column('papers', sa.Column('url', sa.String(), nullable=True))
    op.add_column('papers', sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=False))
    op.alter_column('papers', 'abstract',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_index(op.f('ix_papers_external_id'), 'papers', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_papers_external_id'), table_name='papers')
    op.alter_column('papers', 'abstract',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('papers', 'ingested_at')
    op.drop_column('papers', 'url')
    op.drop_column('papers', 'citation_count')
    op.drop_column('papers', 'doi')
    op.drop_column('papers', 'external_id')
    # ### end Alembic commands ###
